require 'plugins.cmp'
require 'plugins.formatter'
require 'plugins.lsp'
require 'plugins.mini'
require 'plugins.neotree'
require 'plugins.telescope'
require 'plugins.themes'
require 'plugins.which_key'
