vim.pack.add({
	'https://github.com/hrsh7th/nvim-cmp',
	'https://github.com/onsails/lspkind.nvim',
	'https://github.com/hrsh7th/cmp-buffer',
	'https://github.com/hrsh7th/cmp-path',
	'https://github.com/hrsh7th/cmp-cmdline',
	'https://github.com/hrsh7th/cmp-nvim-lua',
	'https://github.com/hrsh7th/cmp-nvim-lsp',
	'https://github.com/saadparwaiz1/cmp_luasnip',
	'https://github.com/L3MON4D3/LuaSnip',
})
